### ISSUE TITLE
ItaxCode.valid? ritorna false per omocodia cittadini estere

### ISSUE THREAD

**Issue by baraidrissa** [matteoredz/itax-code#29]
Ciao @matteoredz , c'è un piccolo problema con i codici fiscale omocodes.

Io ho un codice fiscale reale di un cittadino indiano che finisce con Z2N2Y, però ItaxCode.valid? su questo codice fiscale mi ritorna sempre false.

Ho visto che il metodo [ItaxCode::Validator.new(tax_code, data = {}).valid?](https://github.com/matteoredz/itax-code/blob/main/lib/itax_code/validator.rb#L34) 
controlla che `encoded_tax_code` sia uguale al `tax_code` fornito.
Ovviamente `encoded_tax_code` ritorna un valore che finisce Con codice catastale in questo "Z222N".

Si potrebbe cercare di migliorare questo controllo, altrimenti il programma continuerà a dare false anche per molti altri codici fiscali reali.

Spiego di essermi spiegato.

Grazie mille!

**Comment by matteoredz** [comment]
Ciao @baraidrissa

Inizialmente il controllo era fatto in [questo](https://github.com/matteoredz/itax-code/pull/26/files#diff-01ae7ec4d0be7505255e222e09facc3f99fd5ef3490a215f72137c00ce2198caL32) modo.

Devo fare un po' di test per vedere se reintrodurre questo comportamento sia sufficiente per risolvere il problema senza introdurne altri.

**Comment by matteoredz** [comment]
@baraidrissa ho analizzato la questione, anche confrontando ItaxCode con altre implementazioni, e sono giunto alla conclusione che la validazione del codice fiscale possa (e debba) essere notevolmente semplificata. Ho indicato le motivazioni nella seguente PR https://github.com/matteoredz/itax-code/pull/30.

Data l'entità della modifica, la gemma subirà un bump alla prossima major (attualmente v2.0.0).

**Comment by matteoredz** [comment]
La release [v2.0.0](https://github.com/matteoredz/itax-code/releases/tag/v2.0.0) è stata appena rilasciata! Grazie per il tuo contributo 😄

**Comment by baraidrissa** [comment]
Ciao @matteoredz,
grazie mille a te del gentile riscontro!

Buon inizio settimana
