### ISSUE TITLE
Base error class for errors?

### ISSUE THREAD

**Issue by blocknotes** [matteoredz/itax-code#36]
Hey Matteo 👋 😁 
What about introducing a base class for errors?

For example for these ones: https://github.com/matteoredz/itax-code/blob/d0936b0c8ef34b379af7af24df760ccf2a7d5092/lib/itax_code/parser.rb#L15-L17
The point is that there isn't an easy way to catch all the `ItaxCode` errors if you are not interested to handle the specific cases.

**Comment by matteoredz** [comment]
Hey @blocknotes 👋🏻 

That's indeed a great suggestion, thanks for that. I've just drafted PR #37, let me know WYT 😃
